### ISSUE TITLE
Getting an error when running `balenafin-ify.sh` on Linux raspberrypi 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux

### ISSUE THREAD

**Issue by krasi-georgiev** [balena-os/balenafin-raspbian#8]
```
bash <(curl -L bash <(curl -L https://raw.githubusercontent.com/balena-os/balenafin-raspbian/master/balenafin-ify.sh))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2085  100  2085    0     0  11914      0 --:--:-- --:--:-- --:--:-- 11982
[LOG][63] Importing bintray gpg key...
OK
[LOG][63] Adding balenaFin Raspbian repository...
[LOG][63] Installing required packages...
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease      
Err:3 https://dl.bintray.com/balenaos/raspbian buster InRelease      
  403  Forbidden [IP: 3.127.93.119 443]
Reading package lists... Done                  
E: Failed to fetch https://dl.bintray.com/balenaos/raspbian/dists/buster/InRelease  403  Forbidden [IP: 3.127.93.119 443]
E: The repository 'https://dl.bintray.com/balenaos/raspbian buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by batesenergy** [comment]
We are having the same issue using this script, looks like bintray has been shutdown. We have noticed that you moved repos for the etcher repo have you done the same for this repo as well?

We are trying to get 10 of these out to a customer asap with updated firmware.

**Comment by batesenergy** [comment]
@alexgg can you help us with this issue, seems it should be a quick fix! I can even make the changes and commit.

**Comment by alexgg** [comment]
hi @batesenergy unfortunately it's not only the package provider that needs moving. Newer Raspbian are based on a v5.10 kernel and we have yet to update the balenaFin wireless driver to support it. I will ask our customer success team to contact you see if there is something we can do in the meantime.

**Comment by batesenergy** [comment]
@alexgg We do not use the wireless currently, is there a work around in the meantime without it?

**Comment by krasi-georgiev** [comment]
which the latest raspberian that will work with this script so we use that one in the meanwhile?

**Comment by alexgg** [comment]
hi @krasi-georgiev give me a couple of days to check what options we have internally

**Comment by alexgg** [comment]
HI @krasi-georgiev, I have pushed a branch with the update to Buster (https://github.com/balena-os/balenafin-raspbian/tree/alexgg/sd8887-nxp). Unfortunately the WiFi is not fully functional yet, and it hasn't been tested so we won't be releasing this. You can test with the branch and test yourselves. I don't expect other problems apart from the WiFi but Balena won't be supporting this until it passes our validation tests.

**Comment by krasi-georgiev** [comment]
@alexgg did you delete the branch? I was just about to test it.

**Comment by krasi-georgiev** [comment]
aah I see you merged it. Just run it and all looks good. I Will report in the next few days if anything else besides wifi doesn't work.
